### ISSUE TITLE
500 error when deleting a server

### ISSUE THREAD

**Issue by Bencor29** [Bencor29/pterodactyl-panel-module-support#1]
When a server is associated with a ticket, you got a 500 from pterodactyl when you try to delete the server.

**Comment by ghost** [comment]
a way to remove server option?

**Comment by Bencor29** [comment]
I'll simply add triggers on server deletion to set the ticket's server_id to null.
I don't have the time for the moment but if you want to PR you're welcome ;)

**Comment by Bencor29** [comment]
@lazarsn I'll simply add triggers on server deletion to set the ticket's server_id to null.
I don't have the time for the moment but if you want to PR you're welcome ;)

**Comment by lazarsn** [comment]
files to edit?

**Comment by Bencor29** [comment]
Original incorrect file: https://github.com/Bencor29/pterodactyl-panel-module-support/blob/master/database/migrations/2019_08_11_141118_create_tickets_table.php

Do to list:
- [x] Create a new migration that add the correct triggers
- [x] Make a new "diff" file that contains the plugin' files
- [x] Publish a release

**Comment by Bencor29** [comment]
Update is available
https://github.com/Bencor29/pterodactyl-panel-module-support/releases/tag/v0.7.15-p0.0.2
