### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by ghost** [Bencor29/pterodactyl-panel-module-support#2]
**************************************
*     Application In Production!     *                                          **************************************
 Do you really wish to run this command? (yes/no) [no]:
 > y                                                                            
Migrating: 2019_09_09_182422_add_triggers_to_foreign_on_plugin_tables

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.tickets' doesn't exist (SQL: alter table `tickets` drop foreign key `tickets_server_id_foreign`)

  at /var/www/panel.nyasky.xyz/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error                                                                   661|         // message to include the bindings with SQL, which will make this exception a                                                                      662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.tickets' doesn't exist")
      /var/www/panel.nyasky.xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144

  2   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.tickets' doesn't exist")
      /var/www/panel.nyasky.xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142

**Comment by Bencor29** [comment]
@lazarsn Did you extract all the files from the zipfile or only the migration file ?

**Comment by ghost** [comment]
All files

**Comment by ghost** [comment]
Look like DB side error
I will redo database again

**Comment by ghost** [comment]
Issue fixed
